CREATE DATABASE VENTAS2024
GO
USE VENTAS2024
GO
CREATE TABLE USUARIO
(COD_USUA VARCHAR(6) NOT NULL,
NOM_USUA CHAR (25) NOT NULL,
)
GO

ALTER TABLE USUARIO
ADD COD_EST VARCHAR (25) NOT NULL
go

SELECT *FROM USUARIO
/*INSERTAR DATOS*/
INSERT INTO USUARIO VALUES('U00001' , 'LUIS','ACTIVO')
SELECT*FROM USUARIO
INSERT INTO USUARIO VALUES('U00002' , 'JANO','ACTIVO')
INSERT INTO USUARIO VALUES('U00003' , 'FRANK','INACACTIVO')
INSERT INTO USUARIO VALUES('U00004' , 'LEO','ACTIVO')
INSERT INTO USUARIO VALUES('U00005' , 'JESUS','NULL')
INSERT INTO USUARIO VALUES('U00006' , 'SONIA','ACTIVO')
INSERT INTO USUARIO VALUES('U00007' , 'LESLIE','INACTIVO')
INSERT INTO USUARIO VALUES('U00008' , 'LIZU','ACTIVO')
INSERT INTO USUARIO VALUES('U00009' , 'JOEL','NULL')
INSERT INTO USUARIO VALUES('U00010' , 'BEATRIZ','ACTIVO')
INSERT INTO USUARIO VALUES('U00011' , 'CARLOS','INACTIVO')
SELECT*FROM USUARIO/*MUESTRA LOS REGISTROS DE LA TABLA DE USUSARIO*/
DELETE FROM USUARIO/*BORRA TODOS LOS REGISTROS DE LA TABLA DE USUARIO*/
DELETE FROM USUARIO WHERE COD_USUA= 'U00010'/*BORRO DE LA TABLA DE USUSARIO EL COD U00010*/
  DELETE FROM USUARIO WHERE NOM_USUA= 'JOEL'
  INSERT INTO USUARIO VALUES ('U00009' , 'LIZU' , 'ACTIVO')
    DELETE FROM USUARIO WHERE COD_EST= 'INACTIVO'
GO